/*AULA 05 - PROGRAMA 03 - 13/03/2025
        SEMÁFORO DE UMA RUA
PROGRAMA QUE FAZ A LÓGICA DE UM SEMÁFORO PARA UMA RUA.
O LED VERMELHO COMEÇA LIGADO.
FOI USADO UM LED VERDE NO PINO 7.
FOI USADO UM LED AMARELO NO PINO 6.
FOI USADO UM LED VERMELHO NO PINO 5.
OS RESISTORES USADOS SÃO DE 330R.
PROGRAMA CRIADO PELA NATALIA
*/

#define GREEN 7 //CRIA A VARIÁVEL
#define YELLOW 6 //CRIA A VARIÁVEL
#define RED 5 //CRIA A VARIÁVEL

void setup() // FUNÇÃO EXECUTADA SÓ UMA VEZ
{
  pinMode(GREEN, OUTPUT); //DEFINE COMO SAÍDA
  pinMode(YELLOW, OUTPUT); //DEFINE COM SAÍDA
  pinMode(RED, OUTPUT); //DEFINE COMO SAÍDA
}

void loop() //FUNÇÃO EXECUTADA VARIAS VEZES, PROGRAMAÇÃO
{
  digitalWrite(RED, HIGH); //LIGA O VERMELHO
  delay(10000); //ESPERA 10 SEGUNDOS
  digitalWrite(RED, LOW); //DESLIGA O VERMELHO
  digitalWrite(GREEN, HIGH); //LIGA O VERDE
  delay(8000); //ESPERA 8 SEGUNDOS
  digitalWrite(GREEN, LOW); //DESLIGA O VERDE
  digitalWrite(YELLOW, HIGH); //LIGA O AMARELO
  delay(2000); //ESPERA 2 SEGUNDOS
  digitalWrite(YELLOW, LOW); //DESLIGA O AMARELO
}
